wandb_version: 1

experiment:
  desc: null
  value: data_scaling
model:
  desc: null
  value: facebook/nllb-200-distilled-600M
data_size:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.9.23
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.56.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1758707591.670229
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      - 103
      3:
      - 2
      - 16
      - 23
      4: 3.9.23
      5: 0.15.8
      6: 4.56.2
      8:
      - 5
output_dir:
  desc: null
  value: experiments/data_size_1000
r:
  desc: null
  value: 16
alpha:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 3
batch_size:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0001
use_wandb:
  desc: null
  value: false
eval_steps:
  desc: null
  value: 200
save_steps:
  desc: null
  value: 400
