wandb_version: 1

data_size:
  desc: null
  value: 500
_wandb:
  desc: null
  value:
    python_version: 3.9.23
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.56.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1759058060.884942
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 100
      - 103
      3:
      - 16
      - 23
      4: 3.9.23
      5: 0.15.8
      6: 4.56.2
      8:
      - 5
